# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Vallabh Kansagara ( VRKANSAGARA )
subtitle: Programmer to Programming


# Insert your disqus shortname
<<<<<<< HEAD
#disqus:
#    shortname:

default_date_format: "Y-m-d H:i:s"

authors:
  dk:
    name: Vallabh Kansagara
    title: Software Engineer
    bio: I am another software engineer
    github: https://github.com/vrkansagara
    resume: https://resume.github.io/?vrkansagara
=======
disqus:
    shortname: vrkansagara
>>>>>>> upstream/develop
