sculpin_content_types:
    posts:
        type: path
        path: _posts
        taxonomies:
            - tags
            - categories
        permalink: blog/:year/:month/:day/:filename
        # To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
        enabled: true

    projects:
        type: path
        path: _projects
        singular_name: project
        layout: project
        enabled: true
        permalink: projects/:title
        taxonomies:
            - tags

sculpin_pagination:
    max_per_page: 2
